name: Build-OpenWrt

on:
  repository_dispatch:
#  push:
#    branches: 
#      - master
#  release:
#    types: published
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    timeout-minutes: 3600

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2


    - name: Print Info
      run: |
        echo -e ${GITHUB_WORKSPACE}
        echo -e "${{ toJson(github) }}"
        echo -e "${{ github.event.client_payload.repo }}"
