name: Build-OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
#  push:
#    branches: 
#      - master
#  release:
#    types: published
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    timeout-minutes: 3600

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: NMSL
      run: apt update

    - name: SSH connection to Actions
      uses: csexton/debugger-action@master
