name: Build-OpenWrt

on:
  push:
    branches: 
      - master
#  release:
#    types: published
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    timeout-minutes: 3600

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: Init build dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install gcc-8 gcc++-8 gcc-8-multilib g++-8-multilib 
        for i in $(ls /usr/bin/*-8); do sudo -E ln -sf $i ${i%%-8*}; done 

    - name: Print Info
      run: |
        echo -e ${{ env.GITHUB_WORKSPACE }}
        df -h
        free -h
