name: openwrt

on:
  push:
    branches: 
      - master
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04 
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get remove -y aria2 dotnet* firefox gcc-7 gcc++-7 gcc-7-multilib gcc++-7-multilib google-chrome-stable google-cloud-sdk linux-azure* linux-cloud-tools* linux-modules-* linux-tools-* mysql* php* zulu*
        sudo apt-get autoremove -y
        sudo apt-get update -y
        sudo apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-8 gcc++-8 gcc-8-multilib g++-8-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler
        mkdir -p /home/runner/install
        df -h >/home/runner/install/log
    - uses: actions/upload-artifact@master
      with:
        name: result
        path: /home/runner/install
